[app]
server = ""
port = "8000"

[mode]
development = true

[mysql]
name = "oss"
port = "3306"
server = "127.0.0.1"
username = "root"
password = "rootkeys"
MaxIdleConn = 100  # 最多空闲连接数
MaxOpenConn = 100  # 最多打开连接数

[log]
MaxAge = 30
MaxSize = 100
MaxBackups = 3
LocalTime = true
Compress = true

[redis]
DB = 0
Addr = "localhost:6379"
Username = ""
Password = ""

